### ISSUE TITLE
Container stalls in Kubernetes

### ISSUE THREAD

**Issue by pkrog** [phnmnl/container-biosigner#1]
While run in Kubernetes or minikube the job is never run. Instead there is the following error inside Galaxy pod log (obtained by running `kubectl logs -f galaxy-k8s-<your-suffix>`):
```
galaxy.jobs.runners ERROR 2018-01-17 14:08:41,059 (7) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 107, in queue_job
    "spec": self.__get_k8s_job_spec(job_wrapper)
  File "/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 161, in __get_k8s_job_spec
    k8s_job_spec = {"template": self.__get_k8s_job_spec_template(job_wrapper)}
  File "/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 175, in __get_k8s_job_spec_template
    "containers": self.__get_k8s_containers(job_wrapper)
  File "/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 215, in __get_k8s_containers
    "image": self._find_container(job_wrapper).container_id,
AttributeError: 'NullContainer' object has no attribute 'container_id'
```

**Comment by pkrog** [comment]
In the Galaxy `job_conf.xml`, if the destination is changed from the new dynamic scheme (`dynamic-k8s-*`) to the old scheme:
```
    <destination id="biosigner-container" runner="k8s">
      <param id="docker_repo_override">container-registry.phenomenal-h2020.eu</param>
      <param id="docker_owner_override">phnmnl</param>
      <param id="docker_image_override">biosigner</param>
      <param id="docker_tag_override">v2.2.7_cv1.1.12</param>
      <param id="max_pod_retrials">3</param>
      <param id="docker_enabled">true</param>
    </destination>
```
Then the tool container is run correctly.

**Comment by pcm32** [comment]
Good that we nailed it down to this at least. Probably the best would be to run a galaxy instance with the debugger outside of minikube (but pointing the k8s job runner to the minikube kube_config file) to see why information is not passed fine for the lower level container resolver from Galaxy.

**Comment by pkrog** [comment]
Solved by Pablo.
